import { v4 as uuid } from "uuid";
import tshirt from "../../assets/Products-images/HRX-Yellow-Printed-Round-Neck-T-Shirt--1.webp";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    categories: "men",
    image: { tshirt },
    brand: "HRX",
    name: "Yellow Printed Round Neck",
    discoutPrice: 700,
    actualPrice: 900,
    discout: 40,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
  },
  {
    _id: uuid(),
    categories: "men",
    image: { tshirt },
    brand: "Levis",
    name: "Grey Plain Shirt",
    discoutPrice: 1200,
    actualPrice: 2000,
    discout: 20,
    inStock: true,
    fastDelivery: true,
    ratings: 3.5,
  },
  {
    _id: uuid(),
    categories: "men",
    image: { tshirt },
    brand: "H&M",
    name: "Brown Leather Jacket",
    discoutPrice: 3999,
    actualPrice: 7999,
    discout: 50,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
  },
  {
    _id: uuid(),
    categories: "men",
    image: { tshirt },
    brand: "Nautica",
    name: "Red Plain Kolor Neck",
    discoutPrice: 999,
    actualPrice: 1200,
    discout: 10,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
  },
  {
    _id: uuid(),
    categories: "Women",
    image: { tshirt },
    brand: "Nautica",
    name: "Yellow Printed Long Suit",
    discoutPrice: 2700,
    actualPrice: 3000,
    discout: 20,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
  },
  {
    _id: uuid(),
    categories: "Women",
    image: { tshirt },
    brand: "Roadster",
    name: "Yellow Silk Design Kurta",
    discoutPrice: 1199,
    actualPrice: 1500,
    discout: 30,
    inStock: true,
    fastDelivery: true,
    ratings: 3.5,
  },
  {
    _id: uuid(),
    categories: "Women",
    image: { tshirt },
    brand: "H&M",
    name: "Black Cotton Shrug",
    discoutPrice: 999,
    actualPrice: 1200,
    discout: 30,
    inStock: true,
    fastDelivery: true,
    ratings: 3.5,
  },
  {
    _id: uuid(),
    categories: "Women",
    image: { tshirt },
    brand: "Nautica",
    name: "Dark Blue long Jacket",
    discoutPrice: 700,
    actualPrice: 900,
    discout: 40,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
  },
];
