import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    category: "men",
    image: "/Products-images/HRX-Yellow-Printed-Round-Neck-T-Shirt--1.webp",
    brand: "HRX",
    name: "Yellow Printed Tshirt",
    discountPrice: 700,
    actualPrice: 900,
    discount: 20,
    inStock: true,
    fastDelivery: false,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "men",
    image:
      "/Products-images/-Men-Green-Slim-Fit-Solid-Casual-Shirt-358156645-1.webp",
    brand: "Levis",
    name: "Green Plain Shirt",
    discountPrice: 1200,
    actualPrice: 2000,
    discount: 20,
    inStock: true,
    fastDelivery: true,
    ratings: 3.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "men",
    image: "/Products-images/Leather-Jacket1.webp",
    brand: "H&M",
    name: "Brown Leather Jacket",
    discountPrice: 3999,
    actualPrice: 7999,
    discount: 50,
    inStock: false,
    fastDelivery: false,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "men",
    image: "/Products-images/Nautica-Men-Tshirts-1.webp",
    brand: "Nautica",
    name: "Red Plain Kolor Neck",
    discountPrice: 999,
    actualPrice: 1200,
    discount: 10,
    inStock: false,
    fastDelivery: false,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "women",
    image: "/Products-images/-Women-Kurta-Sets2-1.webp",
    brand: "Nautica",
    name: "Yellow Printed Long Suit",
    discountPrice: 2700,
    actualPrice: 3000,
    discount: 20,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "women",
    image: "/Products-images/women-kurti-nautrica.webp",
    brand: "Nautica",
    name: "Yellow Silk Design Kurta",
    discountPrice: 1199,
    actualPrice: 1500,
    discount: 30,
    inStock: true,
    fastDelivery: true,
    ratings: 3.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "women",
    image: "/Products-images/pink-top.webp",
    brand: "H&M",
    name: "Pink Power Shoulders Top",
    discountPrice: 2700,
    actualPrice: 3000,
    discount: 10,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "women",
    image: "/Products-images/womne-top-hrx.webp",
    brand: "H&M",
    name: "Black Cotton Shrug",
    discountPrice: 999,
    actualPrice: 1200,
    discount: 30,
    inStock: true,
    fastDelivery: true,
    ratings: 3.5,
    size: "L",
  },

  {
    _id: uuid(),
    category: "footwear",
    image: "/Products-images/HRX-Running-Shoe.webp",
    brand: "HRX",
    name: "Running Shoes",
    discountPrice: 5999,
    actualPrice: 6999,
    discount: 10,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "footwear",
    image: "/Products-images/HRX-White-Shoes-sneekers.webp",
    brand: "HRX",
    name: "White Sneekers",
    discountPrice: 2999,
    actualPrice: 6999,
    discount: 20,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "footwear",
    image: "/Products-images/Nike-Shoes.webp",
    brand: "Nike",
    name: "Sports shoes",
    discountPrice: 4999,
    actualPrice: 8999,
    discount: 40,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "footwear",
    image: "/Products-images/NikeMen-Black-Running-Shoes.webp",
    brand: "Nike",
    name: "Running shoes",
    discountPrice: 4999,
    actualPrice: 8999,
    discount: 40,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "homedecor",
    image: "/Products-images/Golden-statue.webp",
    brand: "Regular",
    name: "Golden Ganesh Light",
    discountPrice: 1499,
    actualPrice: 999,
    discount: 30,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "homedecor",
    image: "/Products-images/HomeCentreMultiTableLampsGlass1.webp",
    brand: "Regular",
    name: "Light Lamp",
    discountPrice: 1999,
    actualPrice: 999,
    discount: 50,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "jewellery",
    image: "/Products-images/bangle1.webp",
    brand: "Regular",
    name: "Gold Bangle",
    discountPrice: 1999,
    actualPrice: 999,
    discount: 50,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "footwear",
    image: "/Products-images/Women-White-Flats.webp",
    brand: "Nautica",
    name: "White Flats",
    discountPrice: 1999,
    actualPrice: 999,
    discount: 50,
    inStock: false,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "footwear",
    image: "/Products-images/WomenPinkFlats.webp",
    brand: "Nautica",
    name: "Pink Flats",
    discountPrice: 1999,
    actualPrice: 1599,
    discount: 20,
    inStock: false,
    fastDelivery: true,
    ratings: 3.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "footwear",
    image: "/Products-images/red-heels.webp",
    brand: "Nautica",
    name: "Party Red Block heels",
    discountPrice: 2000,
    actualPrice: 4000,
    discount: 50,
    inStock: false,
    fastDelivery: true,
    ratings: 3.5,
    size: "L",
  },
  {
    _id: uuid(),
    category: "jewellery",
    image: "/Products-images/JewellerySet1.webp",
    brand: "Regular",
    name: "Jewellery Set",
    discountPrice: 4999,
    actualPrice: 3999,
    discount: 20,
    inStock: false,
    fastDelivery: true,
    size: "L",
    ratings: 2.5,
  },
  {
    _id: uuid(),
    category: "jewellery",
    image: "/Products-images/ear-Gold-Toned.webp",
    brand: "Regular",
    name: "Dome Shaped Jhumkas",
    discountPrice: 1000,
    actualPrice: 2000,
    discount: 50,
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
    size: "L",
  },
];
